### ISSUE TITLE
TypeError: Invalid Version: X.X.X

### ISSUE THREAD

**Issue by ntkoopman** [thorbenvh8/prettier-java#31]
I get this error when running prettier on a .java file. It has a fixme in the code [here](https://github.com/thorbenvh8/prettier-java/blob/master/src/index.js#L9) so I'm pretty sure you already know about it.

**Comment by thorbenvh8** [comment]
thats your error? 
if you are in the prettier-java folder and run "yarn prettier ../path/to/*.java" does that work for you?
if you install it through npm you get this error?

**Comment by ntkoopman** [comment]
Yes, I just installed in an empty directory
```sh
yarn add --exact prettier prettier-plugin-java
```
then run it on any .java file will give the following error

```
yarn run v1.5.1
warning package.json: No license field
$ /home/nt/Projects/prettier/node_modules/.bin/prettier RootController.java
/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:1649
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: X.X.X
    at new SemVer (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:1649:11)
    at compare (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:1922:39)
    at Function.gte (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:1971:10)
    at plugins.reduce.filter.language (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:19932:20)
    at Array.filter (<anonymous>)
    at getSupportInfo$1 (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:19929:6)
    at updateContextOptions (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:39657:26)
    at pushContextPlugins (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:39689:3)
    at updateContextArgv (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:39700:3)
    at Object.createContext (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:39641:3)
    at Object.run (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:39737:26)
    at Object.<anonymous> (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:39804:5)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c /home/nt/Projects/prettier/node_modules/.bin/prettier RootController.java
Directory: /home/nt/Projects/prettier
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/nt/Projects/prettier/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
and the resulting packages.json:
```json
{
  "dependencies": {
    "prettier": "1.11.1",
    "prettier-plugin-java": "0.0.2"
  }
}
```

**Comment by j-f1** [comment]
@thorbenvh8 It looks like you have to fill out a version number [here](https://github.com/thorbenvh8/prettier-java/blob/472d244998e20b8be99acebc516b782b46c148da/src/index.js#L9).

**Comment by azz** [comment]
Actually just delete that line. It's not needed anymore

**Comment by thorbenvh8** [comment]
ok great I will delete it :)

**Comment by thorbenvh8** [comment]
@azz 
```javascript
const languages = [
  {
    name: "Java",
    since: "X.X.X", // FIXME
    parsers: ["java"],
    group: "Java",
    tmScope: "text.html.vue", // FIXME
    aceMode: "html", // FIXME
    codemirrorMode: "clike",
    codemirrorMimeType: "text/x-java",
    extensions: [".java"],
    linguistLanguageId: 181,
    vscodeLanguageIds: ["java"]
  }
];
```

Does this look in general good? the other two FIXME things, what should I put there?

**Comment by jdubois** [comment]
Exactly the same issue when trying to use prettier-java with @jhipster ! @thorbenvh8 could you release a new version for this, I think it's broken for everyone?

**Comment by thorbenvh8** [comment]
I will close this, since I fixed this I get an **TypeError: options.locEnd is not a function** error now, and we already have an issue for this.
It comes from comments and somehow my comments are not created correctly so prettier has some trouble with it.
I will create an issue in prettier main project.
