### ISSUE TITLE
TypeError: options.locEnd is not a function

### ISSUE THREAD

**Issue by ntkoopman** [thorbenvh8/prettier-java#32]
Whenever there is a comment in the code (doesn't matter what kind of comment) you get a parse error:

```
TypeError: options.locEnd is not a function
```

**Comment by thorbenvh8** [comment]
can you upload an example file? I have tested it against a code base of 1000+ files and it worked fine with javadoc, traditional comments and line comments.
Even look at the test output here: https://github.com/thorbenvh8/prettier-java/blob/master/PREVIEW.md#comment_javadoc

I believe you, I just would like to know how to test this. are you using windows or unix machine? :)

**Comment by ntkoopman** [comment]
There is nothing special about the files, here is an example file that doesn't work for me:
```java
public class Test {

  public void test() {
    // A comment
    return;
  }
}
```
```
yarn run v1.5.1
warning package.json: No license field
$ /home/nt/Projects/prettier/node_modules/.bin/prettier test.java

[error] test.java: TypeError: options.locEnd is not a function
[error]     at path$$1.each.commentPath (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:9084:44)
[error]     at FastPath.each (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:20088:7)
[error]     at Object.printComments (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:9068:11)
[error]     at printGenerically (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:23398:22)
[error]     at FastPath.map (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:20116:19)
[error]     at printBlock (/home/nt/Projects/prettier/node_modules/prettier-plugin-java/src/printer.js:665:34)
[error]     at printNode (/home/nt/Projects/prettier/node_modules/prettier-plugin-java/src/printer.js:2202:14)
[error]     at Object.genericPrint [as print] (/home/nt/Projects/prettier/node_modules/prettier-plugin-java/src/printer.js:2550:10)
[error]     at genericPrint$6 (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:23462:18)
[error]     at comments.printComments.p (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:23400:14)
[error]     at Object.printComments (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:9058:19)
[error]     at printGenerically (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:23398:22)
[error]     at FastPath.call (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:20062:18)
[error]     at printMethodDeclaration (/home/nt/Projects/prettier/node_modules/prettier-plugin-java/src/printer.js:585:20)
[error]     at printNode (/home/nt/Projects/prettier/node_modules/prettier-plugin-java/src/printer.js:2190:14)
[error]     at Object.genericPrint [as print] (/home/nt/Projects/prettier/node_modules/prettier-plugin-java/src/printer.js:2550:10)
[error]     at genericPrint$6 (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:23462:18)
[error]     at comments.printComments.p (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:23400:14)
[error]     at Object.printComments (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:9058:19)
[error]     at printGenerically (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:23398:22)
[error]     at FastPath.call (/home/nt/Projects/prettier/node_modules/prettier/bin-prettier.js:20062:18)
[error]     at printClassBodyMemberDeclaration (/home/nt/Projects/prettier/node_modules/prettier-plugin-java/src/printer.js:338:18)
error An unexpected error occurred: "Command failed.
Exit code: 2
Command: sh
Arguments: -c /home/nt/Projects/prettier/node_modules/.bin/prettier test.java
Directory: /home/nt/Projects/prettier
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/nt/Projects/prettier/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm using linux, node v9.8.0 and yarn 1.5.1

**Comment by thorbenvh8** [comment]
Yeah thanks great example. Yes the comments have a problem, I will create an issue in the main project and ask for help :) 

https://github.com/prettier/prettier/issues/4217

**Comment by dotlouis** [comment]
Got the same problem
