### ISSUE TITLE
Enums are stripped from their values

### ISSUE THREAD

**Issue by dotlouis** [thorbenvh8/prettier-java#40]
Hello,
Thanks for this great plugin, can't wait to put it all over the codebase.
Although I have an issue with enums. There are stripped of their values:

### Input
```Java
public enum MyEnum {
    GREAT_ENUM("greatValue");
}
```

gives

### Output
```Java
public enum MyEnum {
    GREAT_ENUM;
}
```

Also, I get this stacktrace for the file (not sure if directly related)

````
TypeError: Cannot read property 'declarations' of undefined
[error]     at printEnumDeclaration (/usr/local/lib/node_modules/prettier-plugin-java/src/printer.js:498:17)
[error]     at printNode (/usr/local/lib/node_modules/prettier-plugin-java/src/printer.js:2250:14)
[error]     at Object.genericPrint [as print] (/usr/local/lib/node_modules/prettier-plugin-java/src/printer.js:2652:10)
[error]     at genericPrint$6 (/usr/local/lib/node_modules/prettier/bin-prettier.js:23998:18)
[error]     at comments.printComments.p (/usr/local/lib/node_modules/prettier/bin-prettier.js:23936:14)
[error]     at Object.printComments (/usr/local/lib/node_modules/prettier/bin-prettier.js:8252:19)
[error]     at printGenerically (/usr/local/lib/node_modules/prettier/bin-prettier.js:23934:22)
[error]     at FastPath.call (/usr/local/lib/node_modules/prettier/bin-prettier.js:21082:18)
[error]     at printTypeDeclaration (/usr/local/lib/node_modules/prettier-plugin-java/src/printer.js:97:18)
[error]     at printNode (/usr/local/lib/node_modules/prettier-plugin-java/src/printer.js:2211:14)
[error]     at Object.genericPrint [as print] (/usr/local/lib/node_modules/prettier-plugin-java/src/printer.js:2652:10)
[error]     at genericPrint$6 (/usr/local/lib/node_modules/prettier/bin-prettier.js:23998:18)
[error]     at comments.printComments.p (/usr/local/lib/node_modules/prettier/bin-prettier.js:23936:14)
[error]     at Object.printComments (/usr/local/lib/node_modules/prettier/bin-prettier.js:8252:19)
[error]     at printGenerically (/usr/local/lib/node_modules/prettier/bin-prettier.js:23934:22)
[error]     at FastPath.map (/usr/local/lib/node_modules/prettier/bin-prettier.js:21136:19)
```

**Comment by thorbenvh8** [comment]
I could not get that exception, but I added the arguments to enum constants.
Thanks for reporting :) Seems like you are using this, maybe its time you get your hands dirty and work in this project yourself? :) Just pick up one of the issues to print stuff more pretty!
Use version 0.0.7 please :)
