### ISSUE TITLE
Broken for axis1-java

### ISSUE THREAD

**Issue by Graham42** [thorbenvh8/prettier-java#45]
I get a stacktrace when trying to format `apache/axis1-java` 
(https://github.com/apache/axis1-java/)

Steps: 
1. `git clone https://github.com/apache/axis1-java.git`
2. `prettier  --parser=java --write 'axis1-java/**/*.java'`

Stacktrace:
<details>

```
axis1-java/axis-ant/src/main/java/org/apache/axis/tools/ant/axis/AdminClientTask.java 83ms
axis1-java/axis-ant/src/main/java/org/apache/axis/tools/ant/axis/RunAxisFunctionalTestsTask.java 29ms
axis1-java/axis-ant/src/main/java/org/apache/axis/tools/ant/foreach/ForeachTask.java 27ms
axis1-java/axis-ant/src/main/java/org/apache/axis/tools/ant/foreach/ParamItem.java 6ms
axis1-java/axis-ant/src/main/java/org/apache/axis/tools/ant/foreach/ParamSet.java 17ms
axis1-java/axis-ant/src/main/java/org/apache/axis/tools/ant/wsdl/ComplexType.java 6ms
axis1-java/axis-ant/src/main/java/org/apache/axis/tools/ant/wsdl/Java2WsdlAntTask.java 46ms
axis1-java/axis-ant/src/main/java/org/apache/axis/tools/ant/wsdl/Mapper.java 7ms
axis1-java/axis-ant/src/main/java/org/apache/axis/tools/ant/wsdl/MappingSet.java 4ms
axis1-java/axis-ant/src/main/java/org/apache/axis/tools/ant/wsdl/NamespaceMapping.java 10ms
axis1-java/axis-ant/src/main/java/org/apache/axis/tools/ant/wsdl/TypeMappingVersionEnum.java 2ms
axis1-java/axis-ant/src/main/java/org/apache/axis/tools/ant/wsdl/Wsdl2javaAntTask.java
[error] axis1-java/axis-ant/src/main/java/org/apache/axis/tools/ant/wsdl/Wsdl2javaAntTask.java: Error: Sad sad panda, parsing errors detected in line: 135, column: 23!
[error] Expecting: one of these possible Token sequences:
[error]   1. ['this']
[error]   2. ['super']
[error]   3. ['DecimalLiteral']
[error]   4. ['HexLiteral']
[error]   5. ['OctLiteral']
[error]   6. ['BinaryLiteral']
[error]   7. ['FloatLiteral']
[error]   8. ['HexFloatLiteral']
[error]   9. ['CharLiteral']
[error]   10. ['StringLiteral']
[error]   11. ['true']
[error]   12. ['false']
[error]   13. ['null']
[error]   14. ['@']
[error]   15. [Identifier]
[error]   16. ['boolean']
[error]   17. ['char']
[error]   18. ['byte']
[error]   19. ['short']
[error]   20. ['int']
[error]   21. ['long']
[error]   22. ['float']
[error]   23. ['double']
[error]   24. ['?']
[error]   25. ['(']
[error] but found: '-'
[error]     at Object.parse (/home/grahamm/<snipped-project-dir>/node_modules/chevrotain-java/src/index.js:20:11)
[error]     at Object.parse (/home/grahamm/<snipped-project-dir>/node_modules/prettier-plugin-java/src/parser.js:6:25)
[error]     at Object.parse$3 [as parse] (/home/grahamm/.nvm/versions/node/v8.11.1/lib/node_modules/prettier/bin-prettier.js:23712:19)
[error]     at formatWithCursor (/home/grahamm/.nvm/versions/node/v8.11.1/lib/node_modules/prettier/bin-prettier.js:29396:27)
[error]     at Object.formatWithCursor (/home/grahamm/.nvm/versions/node/v8.11.1/lib/node_modules/prettier/bin-prettier.js:29697:12)
[error]     at format$1 (/home/grahamm/.nvm/versions/node/v8.11.1/lib/node_modules/prettier/bin-prettier.js:35857:21)
[error]     at eachFilename (/home/grahamm/.nvm/versions/node/v8.11.1/lib/node_modules/prettier/bin-prettier.js:36082:16)
[error]     at filePaths.forEach.filePath (/home/grahamm/.nvm/versions/node/v8.11.1/lib/node_modules/prettier/bin-prettier.js:36022:7)
[error]     at Array.forEach (<anonymous>)
[error]     at eachFilename (/home/grahamm/.nvm/versions/node/v8.11.1/lib/node_modules/prettier/bin-prettier.js:36021:15)
[error]     at Object.formatFiles (/home/grahamm/.nvm/versions/node/v8.11.1/lib/node_modules/prettier/bin-prettier.js:36038:3)
[error]     at Object.run (/home/grahamm/.nvm/versions/node/v8.11.1/lib/node_modules/prettier/bin-prettier.js:36663:14)
[error]     at Object.<anonymous> (/home/grahamm/.nvm/versions/node/v8.11.1/lib/node_modules/prettier/bin-prettier.js:36678:5)
[error]     at Module._compile (module.js:652:30)
[error]     at Object.Module._extensions..js (module.js:663:10)
[error]     at Module.load (module.js:565:32)
axis1-java/axis-ant/src/test/java/org/apache/axis/tools/ant/wsdl/CustomGeneratorFactoryTest.java 3ms
axis1-java/axis-ant/src/test/java/org/apache/axis/tools/ant/wsdl/MyGeneratorFactory.java 3ms
axis1-java/axis-ant/src/test/java/org/apache/axis/tools/ant/wsdl/MyServiceImplWriter.java 3ms
axis1-java/axis-ant/src/test/java/org/apache/axis/tools/ant/wsdl/MyServiceWriter.java 3ms
axis1-java/axis-ant/src/test/java/test/wsdl/extra/Extra.java 3ms
axis1-java/axis-ant/src/test/java/test/wsdl/extra/MyService.java 2ms
axis1-java/axis-ant/src/test/java/test/wsdl/groups/GroupsTestCase.java 3ms
axis1-java/axis-ant/src/test/java/test/wsdl/qname/foo.java 1ms
axis1-java/axis-ant/src/test/java/test/wsdl/qname/MyServiceImpl.java 4ms
axis1-java/axis-ant/src/test/java/test/wsdl/qname/MyServiceInterface.java 3ms
axis1-java/axis-ant/src/test/java/test/wsdl/schemaImport/foo.java 1ms
axis1-java/axis-ant/src/test/java/test/wsdl/schemaImport/foobar.java 2ms
axis1-java/axis-ant/src/test/java/test/wsdl/schemaImport/SchemaImportTestCase.java 6ms
axis1-java/axis-ant/src/test/java/test/wsdl/split/MyPortType.java 2ms
axis1-java/axis-ant/src/test/java/test/wsdl/split/SplitTestCase.java 4ms
axis1-java/axis-codegen/src/main/java/org/apache/axis/wsdl/toJava/DuplicateFileException.java 2ms
axis1-java/axis-codegen/src/main/java/org/apache/axis/wsdl/toJava/Emitter.java 44ms
axis1-java/axis-codegen/src/main/java/org/apache/axis/wsdl/toJava/FactoryProperty.java 4ms
axis1-java/axis-codegen/src/main/java/org/apache/axis/wsdl/toJava/GeneratedFileInfo.java 11ms
axis1-java/axis-codegen/src/main/java/org/apache/axis/wsdl/toJava/JavaBeanFaultWriter.java 6ms
axis1-java/axis-codegen/src/main/java/org/apache/axis/wsdl/toJava/JavaBeanHelperWriter.java 26ms
axis1-java/axis-codegen/src/main/java/org/apache/axis/wsdl/toJava/JavaBeanWriter.java 115ms
axis1-java/axis-codegen/src/main/java/org/apache/axis/wsdl/toJava/JavaBindingWriter.java 11ms
axis1-java/axis-codegen/src/main/java/org/apache/axis/wsdl/toJava/JavaBuildFileWriter.java 10ms
axis1-java/axis-codegen/src/main/java/org/apache/axis/wsdl/toJava/JavaClassWriter.java 10ms
axis1-java/axis-codegen/src/main/java/org/apache/axis/wsdl/toJava/JavaDefinitionWriter.java 16ms
axis1-java/axis-codegen/src/main/java/org/apache/axis/wsdl/toJava/JavaDeployWriter.java
[error] Unable to expand glob patterns: axis1-java/**/*.java !**/node_modules/** !./node_modules/**
[error] Cannot read property 'stack' of undefined
```

</details>

**Comment by thorbenvh8** [comment]
This is not crazy at all! Thats exactly how it should be used! ;)
I have been using it like that on a couple of projects before and resolved all problems.

But I see a lot of different error messages, not only that one youre displaying.
Seems like more work for the next weekend ;)

If you want to try yourself, I see some easy ones, like 
```
Unknown Java node: { type: '...', ... }
```

When you do them please create an issue for them, so we don't fix the same thing :)

Thats always when I there is no printFunction for this type yet.

**Comment by thorbenvh8** [comment]
Closing this, for more detailed issues :)

**Comment by Graham42** [comment]
Sounds good, I'll open more specific issues as I find them
