### ISSUE TITLE
Crash for fn in expression in condition, followed by an assignment with a fn call

### ISSUE THREAD

**Issue by Graham42** [thorbenvh8/prettier-java#58]
This is as minimal an example as I could find.  
Crashes when we have a function call in an expression in a condition, followed by an assignment with a function call.
```java
public class MyTest {

	public void myTest(String message) {

		if (message.indexOf('h') > 0) {

		}

		int destination = message.indexOf('d');
	}
}
```
Stacktrace
```
[error] MyTest.java: Error: Sad sad panda, parsing errors detected in line: 7, column: 81!
[error] Expecting --> ')' <-- but found --> ';' <--
[error]     at Object.parse (/home/grahamm/<snipped-project-dir>/node_modules/chevrotain-java/src/index.js:20:11)
[error]     at Object.parse (/home/grahamm/<snipped-project-dir>/node_modules/prettier-plugin-java/src/parser.js:6:25)
[error]     at Object.parse$3 [as parse] (/home/grahamm/<snipped-project-dir>/node_modules/prettier/bin-prettier.js:23712:19)
[error]     at formatWithCursor (/home/grahamm/<snipped-project-dir>/node_modules/prettier/bin-prettier.js:29396:27)
[error]     at Object.formatWithCursor (/home/grahamm/<snipped-project-dir>/node_modules/prettier/bin-prettier.js:29697:12)
[error]     at format$1 (/home/grahamm/<snipped-project-dir>/node_modules/prettier/bin-prettier.js:35857:21)
[error]     at eachFilename (/home/grahamm/<snipped-project-dir>/node_modules/prettier/bin-prettier.js:36082:16)
[error]     at filePaths.forEach.filePath (/home/grahamm/<snipped-project-dir>/node_modules/prettier/bin-prettier.js:36022:7)
[error]     at Array.forEach (<anonymous>)
[error]     at eachFilename (/home/grahamm/<snipped-project-dir>/node_modules/prettier/bin-prettier.js:36021:15)
[error]     at Object.formatFiles (/home/grahamm/<snipped-project-dir>/node_modules/prettier/bin-prettier.js:36038:3)
[error]     at Object.run (/home/grahamm/<snipped-project-dir>/node_modules/prettier/bin-prettier.js:36663:14)
[error]     at Object.<anonymous> (/home/grahamm/<snipped-project-dir>/node_modules/prettier/bin-prettier.js:36678:5)
[error]     at Module._compile (module.js:652:30)
[error]     at Object.Module._extensions..js (module.js:663:10)
[error]     at Module.load (module.js:565:32)
```

**Comment by thorbenvh8** [comment]
Yes looking at the same thing right now ;) seems like my regex for charLiteral is bad :)

**Comment by thorbenvh8** [comment]
Fixed in next release :)
